secrets:
  - value_from: /${APP_NAME}/${ENV}/db_hostname
    name: RDS_HOSTNAME
  - value_from: /${APP_NAME}/${ENV}/db_username
    name: RDS_USERNAME
  - value_from: /${APP_NAME}/${ENV}/db_password
    name: RDS_PASSWORD
  - value_from: /${APP_NAME}/${ENV}/redis_hostname
    name: REDIS_HOSTNAME
  - value_from: /${APP_NAME}/${ENV}/secret_key_base
    name: SECRET_KEY_BASE
  - value_from: /${APP_NAME}/${ENV}/twitter_api_key
    name: TWITTER_API_KEY
  - value_from: /${APP_NAME}/${ENV}/twitter_api_secret
    name: TWITTER_API_SECRET
  - value_from: /${APP_NAME}/${ENV}/google_api_key
    name: GOOGLE_API_KEY
  - value_from: /${APP_NAME}/${ENV}/rollbar_access_token
    name: ROLLBAR_ACCESS_TOKEN
  - value_from: /${APP_NAME}/${ENV}/smtp_username
    name: SMTP_USERNAME
  - value_from: /${APP_NAME}/${ENV}/smtp_password
    name: SMTP_PASSWORD
  - value_from: /${APP_NAME}/${ENV}/batch_username
    name: BATCH_USERNAME
  - value_from: /${APP_NAME}/${ENV}/batch_password
    name: BATCH_PASSWORD
